name: Makefile CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        Target:
          - pine64-pinephone.img.xz
          - pine64-pinetab.img.xz
    steps:
    - uses: actions/checkout@v3
          
    - name: Build image
      env:
        TARGET: ${{matrix.Target}}
      run: make $TARGET
      
    - uses: actions/upload-artifact@v2
      with:
        name: Build result
        path: ${{matrix.Target}}
